server:
  port: 9033

spring:
  application:
    name: file-manage
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=172.30.3.220)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=mdkbuat)))
    username: iocimport
    password: QYdb2019
    ##type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
  freemarker:
    template-loader-path: classpath:/templates
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:9022/eureka/
      defaultZone: http://192.168.80.88:9044/eureka/
  instance:
    #是否优先使用服务实例的IP地址，相较于hostname
    prefer-ip-address: true
    #该服务实例在注册中心的唯一实例ID
    instance-id:  (${spring.cloud.client.ip-address}:${server.port})
    #该服务实例向注册中心发送心跳间隔（s）
    lease-renewal-interval-in-seconds: 10

ribbon:
  eureka:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

pagehelper:
  helperDialect: oracle9i
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

swagger:
  enable: true

file:
  max-file-size: 50
  max-request-size: 500

#fdfs客户端配置
fdfs:
  tracker-server: 172.30.3.48:22122
  domain-name: http://imagecs.quanyou.com.cn/
